#!/bin/sh

# To kill the process (since it's in Valgrind and doesn't always quit):
#
# ps auwxx | grep -i skyd | grep -v grep | awk '{print $2}' | xargs kill -9

OUTFILE=bin/callgrind.out

# Cleanup.
rm -f $OUTFILE

# Start the server.
valgrind --tool=callgrind \
--callgrind-out-file=$OUTFILE \
--dump-instr=yes \
--collect-jumps=yes \
bin/skyd
